--- @meta stubs_cs2dlua_alias

--- Numeric keys [`0`-`9`] that can be used by the [addbind](lua://addbind) function.
--- @alias bind_key_numeric
--- | 0
--- | 1
--- | 2
--- | 3
--- | 4
--- | 5
--- | 6
--- | 7
--- | 8
--- | 9

--- Alphabetic keys [`A`-`Z`] that can be used by the [addbind](lua://addbind) function.
--- @alias bind_key_alphabetic
--- | 'A'
--- | 'B'
--- | 'C'
--- | 'D'
--- | 'E'
--- | 'F'
--- | 'G'
--- | 'H'
--- | 'I'
--- | 'J'
--- | 'K'
--- | 'L'
--- | 'M'
--- | 'N'
--- | 'O'
--- | 'P'
--- | 'Q'
--- | 'R'
--- | 'S'
--- | 'T'
--- | 'U'
--- | 'V'
--- | 'W'
--- | 'X'
--- | 'Y'
--- | 'Z'

--- Function keys [`F1`-`F12`] that can be used by the [addbind](lua://addbind) function.
--- @alias bind_key_function
--- | "F1"
--- | "F2"
--- | "F3"
--- | "F4"
--- | "F5"
--- | "F6"
--- | "F7"
--- | "F8"
--- | "F9"
--- | "F10"
--- | "F11"
--- | "F12"

--- Mouse buttons that can be used by the [addbind](lua://addbind) function.
--- @alias bind_key_mouse
--- | "mouse1" # Left Click.
--- | "mouse2" # Right Click.
--- | "mouse3" # Middle Click.
--- | "mwheelup" # Mouse Wheel Up.
--- | "mwheeldown" # Mouse Wheel Down.

--- System keys that can be used by the [addbind](lua://addbind) function.
--- @alias bind_key_special
--- | "leftshift" # Left Shift.
--- | "rightshift" # Right Shift.
--- | "leftctrl" # Left Control.
--- | "rightctrl" # Right Control.
--- | "leftalt" # Left Alt.
--- | "rightalt" # Right Alt.
--- | "leftsys" # Left System.
--- | "rightsys" # Right System.

--- Arrow keys that can be used by the [addbind](lua://addbind) function.
--- @alias bind_key_arrow
--- | "leftarrow" # ←
--- | "rightarrow" # →
--- | "uparrow" # ↑
--- | "downarrow" # ↓

--- Miscellaneous keys like that can be used by the [addbind](lua://addbind) function.
--- @alias bind_key_misc
--- | "backspace" # Backspace.
--- | "tab" # TAB.
--- | "clear" # Numpad: Clear (5).
--- | "enter" # Enter/Return.
--- | "escape" # Escape.
--- | "space" # Space.
--- | "pgup" # Page up or Numpad: Page up (9).
--- | "pgdn" # Page down or Numpad: Page down (3).
--- | "end" # End or Numpad: End (1).
--- | "home" # Home.
--- | "select" # Legacy key to select text.
--- | "print" # Legacy key to print documents.
--- | "execute" # Legacy key to execute programs/macro.
--- | "screen" # Print screen (cannot be used because windows overrides it).
--- | "ins" # Insert.
--- | "del" # Delete.
--- | "kp_leftarrow" # Numpad: ← (4)
--- | "kp_rightarrow" # Numpad: → (6)
--- | "kp_uparrow" # Numpad: ↑ (8)
--- | "kp_downarrow" # Numpad: ↓ (2)
--- | "kp_home" # Numpad: Home. (7)
--- | "kp_ins" # Numpad: Insert. (0)
--- | "kp_0" # Numpad: 0.
--- | "kp_1" # Numpad: 1.
--- | "kp_2" # Numpad: 2.
--- | "kp_3" # Numpad: 3.
--- | "kp_4" # Numpad: 4.
--- | "kp_5" # Numpad: 5.
--- | "kp_6" # Numpad: 6.
--- | "kp_7" # Numpad: 7.
--- | "kp_8" # Numpad: 8.
--- | "kp_9" # Numpad: 9.
--- | "kp_divide" # Numpad: Divide.
--- | "kp_multiply" # Numpad: Multiply.
--- | "kp_del" # Numpad: Delete. (.)

--- All keys that can be used by the [addbind](lua://addbind) function.
--- @alias bind_key_types
--- | bind_key_numeric
--- | bind_key_alphabetic
--- | bind_key_function
--- | bind_key_mouse
--- | bind_key_special
--- | bind_key_arrow
--- | bind_key_misc

--- Generic binary value.
--- @alias binary_value
--- | 0
--- | 1

--- Category that contains the basic hooks.
--- @alias hook_type_basic
--- | "break" # (```tile_x, tile_y, player_id?```)
--- | "endround" # (```mode_id, delay_ms```)
--- | "httpdata" (```request_id, state, data```)
--- | "log" # (```text```) **->** `0`: proceed normally **|** `1`: don't log this line (this only affects logging, console output can not be controlled with it)
--- | "mapchange" # (```new_map```)
--- | "parse" # (```text```) **->** `0`: proceed normally **|** `1`: normal parsing, ignore unknown cmds **|** `2`: skip CS2D parsing
--- | "post_endround"
--- | "projectile" # (```player_id?, weapon_type_id, x, y, projectile_id```)
--- | "projectile_impact" # (```player_id?, weapon_type_id, x, y, mode, projectile_id```)
--- | "rcon" # (```commands, player_id?, ip, port```)
--- | "shutdown"
--- | "startround" # (```mode```)
--- | "startround_prespawn" # (```mode```)
--- | "trigger" # (```trigger_name, source```) **->** `0`: proceed normally **|** `1`: don't trigger
--- | "triggerentity" # (```tile_x, tile_y```) **->** `0`: proceed normally **|** `1`: don't trigger

--- Category that contains the time hooks.
--- @alias hook_type_time
--- | "always"
--- | "frame"
--- | "minute"
--- | "ms100"
--- | "second"

--- Category that contains anything involving the player.
--- @alias hook_type_player
--- | "assist" # (```assistant_id, victim_id, killer_id```) **->** `0`: proceed normally (count and display assist) **|** `1`: don't count and display the assist (the related kill will be displayed and counted normally but without assist)
--- | "attack" # (```player_id```)
--- | "attack2" # (```player_id, weapon_mode```)
--- | "bombdefuse" # (```player_id```) **->** `0`: proceed normally **|** `1`: don't defuse
--- | "bombexplode" # (```player_id, explosion_tx, explosion_ty```) **->** `0`: proceed normally **|** `1`: don't explode
--- | "bombplant" # (```player_id, bomb_tx, bomb_ty```)  **->** `0`: proceed normally **|** `1`: don't plant
--- | "build" # (```player_id, building_type, building_tx, building_ty, building_mode, object_id```) **->** `0`: proceed normally **|** `1`: don't build
--- | "buildattempt" # (```player_id, building_type, building_tx, building_ty, building_mode```) **->** `0`: proceed normally **|** `1`: don't build
--- | "buy" # (```player_id, weapon_type_id```) **->** `0`: proceed normally **|** `1`: don't allow buying
--- | "clientdata" # (```player_id, mode, data1, data2```)
--- | "clientsetting" # (```player_id, setting, value1, value2```)
--- | "collect" # (```player_id, item_id, item_type_id, ammo_in, ammo, item_mode```)
--- | "connect" # (```player_id```)
--- | "connect_attempt" # (```name, ip, port, usgn_id, usgn_name, steam_id, steam_name```) **->** `""`: (nothing) continue normally **|** `anything else`: cancel the connection process. Client will see a ban popup and the returned string will be displayed as ban reason
--- | "connect_initplayer" # (```player_id```)
--- | "die" # (```victim_id, killer_id?, weapon_type_id/special_source_id, death_x, death_y, killer_object_id```) **->** `0`: proceed normally (and drop stuff depending on settings) **|** `1`: drop bomb/flag only (all other carried items will get lost)
--- | "disconnect" # (```player_id, reason_id```)
--- | "dominate" # (```player_id, team, domination_tx, domination_ty```) **->** `0`: proceed normally **|** `1`: don't dominate
--- | "drop" # (```player_id, item_id, item_type_id, ammo_in, ammo, weapon_mode, drop_tx, drop_ty```) **->** `0`: proceed normally (drop?) **|** `1`: don't drop the item
--- | "flagcapture" # (```player_id, team, flag_tx, flag_ty```) **->** `0`: proceed normally **|** `1`: don't capture flag
--- | "flagtake" # (```player_id, team, flag_tx, flag_ty```) **->** `0`: proceed normally **|** `1`: don't take flag
--- | "flashlight" # (```player_id, state```)
--- | "hit" # (```victim_id, source_id?, weapon_type_id, hp_dmg, ap_dmg, raw_dmg, object_id?```) **->** `0`: proceed normally **|** `1`: ignore this hit (no damage)
--- | "hostagedamage" # (```player_id, hostage_id, damage```) **->** `0`: proceed normally (hurt hostage with fine) **|** `1`: skip entirely (don't hurt and no fine) **|** `2`: hurt without fine
--- | "hostagekill" # (```player_id, hostage_id, damage```) **->** `0`: proceed normally (kill hostage with punishment and radio message) **|** `1`: no punishment but radio (kill hostage with radio message but no fine/punishment) **|** `2`: no punishment and no radio (kill hostage but without radio message and without fine/punishment)
--- | "hostagerescue" # (```player_id, rescue_tx, rescue_ty```)
--- | "hostageuse" # (```player_id, hostage_id, mode```) **->** `0`: proceed normally (start/stop follow if possible) **|** `1`: don't start/stop follow
--- | "itemfadeout" # (```item_id, item_type_id, item_tx, item_ty```) **->** `0`: proceed normally (fade out the weapon) **|** `1`: don't fade out the weapon (droptimer will be set to 10000)
--- | "join" # (```player_id```)
--- | "key" # (```player_id, key, state```)
--- | "kill" # (```killer_id?, victim_id, weapon_type_id, death_x, death_y, killer_obj_id, assistant_id```)
--- | "leave" # (```player_id, reason```)
--- | "menu" # (```player_id, title, button_id```)
--- | "move" # (```player_id, x, y, walk```)
--- | "movetile" # (```player_id, tx, ty```)
--- | "name" # (```player_id, old_name, new_name, forced```) **->** `0`: proceed normally **|** `1`: don't change name
--- | "radio" # (```player_id, message_id```) **->** `0`: proceed normally **|** `1`: don't show message
--- | "reload" # (```player_id, mode```)
--- | "say" # (```player_id, message```) **->** `0`: proceed normally **|** `1`: don't show message
--- | "sayteam" # (```player_id, message```) **->** `0`: proceed normally **|** `1`: don't show message
--- | "sayteamutf8" # (```player_id, message_utf8```) **->** `0`: proceed normally **|** `1`: don't show message
--- | "sayutf8" # (```player_id, message_utf8```) **->** `0`: proceed normally **|** `1`: don't show message
--- | "select" # (```player_id, item_type_id, item_mode```)
--- | "serveraction" # (```player_id, action_key```)
--- | "shieldhit" # (```player_id, source_id, weapon_type_id/source_type_id, attack_direction, attacker_object_id, damage```)
--- | "spawn" # (```player_id```) **->** `""`: (nothing) spawn with regular items **|** `"x"`: spawn with melee weapon only **|** `"typeid,typeid,..."`: spawn with these items + melee
--- | "specswitch" # (```player_id, target_id```)
--- | "spray" # (```player_id```)
--- | "suicide" # (```player_id```) **->** `0`: proceed normally **|** `1`: don't commit suicide
--- | "team" # (```player_id, team_id, look_id```) **->** `0`: proceed normally **|** `1`: don't change team + close menu
--- | "use" # (```player_id, event_id, data, use_tx, use_ty```)
--- | "usebutton" # (```player_id, button_tx, button_ty```)
--- | "vipescape" # (```player_id, escape_tx, escape_ty```)
--- | "voice" # (```player_id```) **->** `0`: proceed normally **|** `1`: disallow voice chat
--- | "vote" # (```player_id, vote_mode, param```) **->** `0`: proceed normally **|** `1`: ignore the vote and do nothing
--- | "walkover" # (```player_id, item_id, item_type_id, ammo_in, ammo, item_mode```) **->** `0`: proceed normally (collect if possible) **|** `1`: don't collect

--- Category that contains anything involving objects.
--- @alias hook_type_object
--- | "hitzone" # (```image_id, player_id?, object_id?, weapon_type_id, impact_x, impact_y, damage```) **->** `0`: proceed normally (without changing the damage) **|** `>0`: set damage to this value **|** `<0`: set damage to 0
--- | "objectdamage" # (```object_id, damage, player_id?```) **->** `0`: proceed normally **|** `1`: don't damage/heal/repair object
--- | "objectkill" # (```object_id, player_id?```)
--- | "objectupgrade" # (```object_id, player_id?, progress, total```) **->** `0`: proceed normally **|** `1`: don't upgrade object
--- | "turretscan" # (```turret_object_id, turret_team, turret_x_position, turret_y_position```) **->** `0`: proceed normally (normal scan & attack closest enemy player) **|** `1-32`: attack player with that ID (may not cause damage depending on team) **|** `-1`: stay idle and attack nobody

--- Category that contains anything involving physics.
--- @alias hook_type_physics
--- | "oncollision" # (```body_a, body_b```)
--- | "oncollisionhit" # (```body_a, body_b, velocity```)
--- | "onhit" # (```physic_id, player_id, weapon_type_id, source_x, source_y, damaged, dynamic_object_id```)

--- All possible hook values.
--- @alias hook_types
--- | hook_type_basic
--- | hook_type_time
--- | hook_type_player
--- | hook_type_object
--- | hook_type_physics

--- Dynamic objects: Class 1: Buildings.
--- @alias dynamic_object_type_id_buildings
--- | 1 # Barricade
--- | 2 # Barbed Wire
--- | 3 # Wall I
--- | 4 # Wall II
--- | 5 # Wall III
--- | 6 # Gate Field
--- | 7 # Dispenser
--- | 8 # Turret
--- | 9 # Supply
--- | 10 # Build Place
--- | 11 # Dual Turret
--- | 12 # Triple Turret
--- | 13 # Teleporter Entrance
--- | 14 # Teleporter Exit
--- | 15 # Super Supply

--- Dynamic objects: Class 2: Stuff.
--- @alias dynamic_object_type_id_stuff
--- | 20 # Mine
--- | 21 # Laser Mine
--- | 22 # Portal 1 (orange)
--- | 23 # Portal 2 (blue)

--- Dynamic objects: Class 3: Units.
--- @alias dynamic_object_type_id_units
--- | 30 # NPC

--- Dynamic objects: Class 4: Images.
--- @alias dynamic_object_type_id_images
--- | 40 # Dynamic Image

--- Dynamic object number identifier types.
--- @alias dynamic_object_type_id_types
--- | dynamic_object_type_id_buildings
--- | dynamic_object_type_id_stuff
--- | dynamic_object_type_id_units
--- | dynamic_object_type_id_images

--- List of primary (slot 1) items.
--- @alias item_type_id_primary
--- | 10 # M3
--- | 11 # XM1014
--- | 20 # MP5
--- | 21 # TMP
--- | 22 # P90
--- | 23 # Mac 10
--- | 24 # UMP45
--- | 30 # AK-47
--- | 31 # SG552
--- | 32 # M4A1
--- | 33 # Aug
--- | 34 # Scout
--- | 35 # AWP
--- | 36 # G3SG1
--- | 37 # SG550
--- | 38 # Galil
--- | 39 # Famas
--- | 40 # M249
--- | 41 # Tactical Shield
--- | 45 # Laser
--- | 46 # Flamethrower
--- | 47 # RPG Launcher
--- | 48 # Rocket Launcher
--- | 49 # Grenade Launcher
--- | 88 # Portal Gun
--- | 90 # M134
--- | 91 # FN F2000
--- | 92 # Tesla Coil

--- List of secondary (slot 2) items.
--- @alias item_type_id_secondary
--- | 1  # USP
--- | 2  # Glock
--- | 3  # Deagle
--- | 4  # P228
--- | 5  # Elite
--- | 6  # Five-Seven

--- List of melee (slot 3) items.
--- @alias item_type_id_melee
--- | 50 # Knife
--- | 69 # Machete
--- | 74 # Wrench
--- | 78 # Claw
--- | 85 # Chainsaw

--- List of explosives (slot 4) items.
--- @alias item_type_id_explosives
--- | 51 # HE
--- | 52 # Flashbang
--- | 53 # Smoke Grenade
--- | 54 # Flare
--- | 55 # Bomb
--- | 72 # Gas Grenade
--- | 73 # Molotov Cocktail
--- | 75 # Snowball
--- | 76 # Air Strike
--- | 77 # Mine
--- | 86 # Gut Bomb
--- | 87 # Laser Mine
--- | 89 # Satchel Charge

--- List of miscellaneous (slot 5/armour/equipment/special) items.
--- @alias item_type_id_miscellaneous
--- | 56 # Defuse Kit
--- | 57 # Kevlar
--- | 58 # Kevlar+Helm
--- | 59 # Night Vision
--- | 60 # Gas Mask
--- | 61 # Primary Ammo
--- | 62 # Secondary Ammo
--- | 63 # Planted Bomb
--- | 64 # Medikit
--- | 65 # Bandage
--- | 66 # Coins
--- | 67 # Money
--- | 68 # Gold
--- | 70 # Red Flag
--- | 71 # Blue Flag
--- | 79 # Light Armour
--- | 80 # Armour
--- | 81 # Heavy Armour
--- | 82 # Medic Armour
--- | 83 # Super Armour
--- | 84 # Stealth Suit

--- All item type number identifier values.
--- @alias item_type_id_types
--- | item_type_id_primary
--- | item_type_id_secondary
--- | item_type_id_melee
--- | item_type_id_explosives
--- | item_type_id_miscellaneous

--- List of all possible player number identifiers.
--- @alias player_id
--- | 0 # Used by the server instance or when no player is specified.
--- | 1  # Player carrying identifier number 1.
--- | 2  # Player carrying identifier number 2.
--- | 3  # Player carrying identifier number 3.
--- | 4  # Player carrying identifier number 4.
--- | 5  # Player carrying identifier number 5.
--- | 6  # Player carrying identifier number 6.
--- | 7  # Player carrying identifier number 7.
--- | 8  # Player carrying identifier number 8.
--- | 9  # Player carrying identifier number 9.
--- | 10 # Player carrying identifier number 10.
--- | 11 # Player carrying identifier number 11.
--- | 12 # Player carrying identifier number 12.
--- | 13 # Player carrying identifier number 13.
--- | 14 # Player carrying identifier number 14.
--- | 15 # Player carrying identifier number 15.
--- | 16 # Player carrying identifier number 16.
--- | 17 # Player carrying identifier number 17.
--- | 18 # Player carrying identifier number 18.
--- | 19 # Player carrying identifier number 19.
--- | 20 # Player carrying identifier number 20.
--- | 21 # Player carrying identifier number 21.
--- | 22 # Player carrying identifier number 22.
--- | 23 # Player carrying identifier number 23.
--- | 24 # Player carrying identifier number 24.
--- | 25 # Player carrying identifier number 25.
--- | 26 # Player carrying identifier number 26.
--- | 27 # Player carrying identifier number 27.
--- | 28 # Player carrying identifier number 28.
--- | 29 # Player carrying identifier number 29.
--- | 30 # Player carrying identifier number 30.
--- | 31 # Player carrying identifier number 31.
--- | 32 # Player carrying identifier number 32.

--- List of all possible player number identifiers.
--- @alias player_team_type_id
--- | 0 # Spectator
--- | 1 # Terrorist
--- | 2 # Counter-Terrorist - ⚠️ **Attention**: May include the VIP. Check function notes.
--- | 3 # VIP - ⚠️ **Attention**: Some functions may include the VIP with the Counter-Terrorists. Check function notes.

--- Radio messages (`I` menu).
--- @alias radio_message_type_id
--- | 6  # Cover Me - `"../sfx/radio/coverme.ogg"`
--- | 32 # You Take the Point - `"../sfx/radio/takepoint.ogg"`
--- | 23 # Hold this Position - `"../sfx/radio/position.ogg"`
--- | 24 # Regroup Team - `"../sfx/radio/regroup.ogg"`
--- | 13 # Follow Me - `"../sfx/radio/followme.ogg"`
--- | 11 # Taking Fire, Need Assistance - `"../sfx/radio/fireassis.ogg"`

--- Group radio messages (`O` menu).
--- @alias group_radio_message_type_id
--- | 15 # Go - `"../sfx/radio/go.ogg"`
--- | 10 # Fall Back - `"../sfx/radio/fallback.ogg"`
--- | 30 # Stick Together Team - `"../sfx/radio/sticktog.ogg"`
--- | 14 # Get in Position - `"../sfx/radio/getinpos.ogg"`
--- | 31 # Storm the Front - `"../sfx/radio/stormfront.ogg"`
--- | 25 # Report In - `"../sfx/radio/reportin.ogg"`

--- Report radio messages (`P` menu).
--- @alias report_radio_message_type_id
--- | 0  # Affirmative - `"../sfx/radio/affirm.ogg"`
--- | 28 # Roger  - `"../sfx/radio/roger.ogg"`
--- | 9  # Enemy Spotted - `"../sfx/radio/enemys.ogg"`
--- | 1  # Need Backup - `"../sfx/radio/backup.ogg"`
--- | 5  # Sector Clear - `"../sfx/radio/clear.ogg"`
--- | 17 # I'm in Position - `"../sfx/radio/inpos.ogg"`
--- | 26 # Reporting In - `"../sfx/radio/reportingin.ogg"`
--- | 2  # She's gonna Blow! - `"../sfx/radio/blow.ogg"`
--- | 22 # Negative - `"../sfx/radio/negative.ogg"`
--- | 8  # Enemy Down - `"../sfx/radio/enemydown.ogg"`

--- Game radio messages (sent automatically by the game).
---
--- ⚠️ **Attention**: You are not meant to use the `radio` hook with these, albeit some of them will call it.
--- @alias game_radio_message_type_id
--- | 3 # Bomb has been defused! - `"../sfx/radio/bombdef.ogg"` - ⚠️ **Attention**: Does not trigger the `radio` hook.
--- | 4 # Bomb has been planted! - `"../sfx/radio/bombpl.ogg"` - ⚠️ **Attention**: Does not trigger the `radio` hook.
--- | 7 # Counter-Terrorists Win - `"../sfx/radio/ctwin.ogg"` - ⚠️ **Attention**: Does not trigger the `radio` hook.
--- | 12 # Fire in the hole! - `"../sfx/radio/fireinhole.ogg"`
--- | 16 # Hostage down! - `"../sfx/radio/hosdown.ogg"`
--- | 18 # Okay, let's go! - `"../sfx/radio/letsgo.ogg"` - ⚠️ **Attention**: Does not trigger the `radio` hook.
--- | 19 # Lock and load! - `"../sfx/radio/locknload.ogg"` - ⚠️ **Attention**: Does not trigger the `radio` hook.
--- | 20 # Teammate down! - `"../sfx/radio/matedown.ogg"`
--- | 21 # Alright, let's move out! - `"../sfx/radio/moveout.ogg"` - ⚠️ **Attention**: Does not trigger the `radio` hook.
--- | 27 # Hostage has been rescued! - `"../sfx/radio/rescued.ogg"`
--- | 29 # Round draw! - `"../sfx/radio/rounddraw.ogg"` - ⚠️ **Attention**: Does not trigger the `radio` hook.
--- | 33 # Terrorists Win - `"../sfx/radio/terwin.ogg"` - ⚠️ **Attention**: Does not trigger the `radio` hook.
--- | 34 # Protect the V.I.P . Team! - `"../sfx/radio/vip.ogg"` - ⚠️ **Attention**: Does not trigger the `radio` hook.

--- All possible radio messages.
--- @alias radio_message_type_id_types
--- | radio_message_type_id
--- | group_radio_message_type_id
--- | report_radio_message_type_id
--- | game_radio_message_type_id

--- @todo document each command
-- Console settings that can be executed by the [parse](lua://parse) function.
--- @alias console_command
--- | "ah"
--- | "ak47"
--- | "alias"
--- | "aliases"
--- | "attack"
--- | "attack2"
--- | "aug"
--- | "autobuy"
--- | "autoscreen"
--- | "autoswitch"
--- | "awp"
--- | "back"
--- | "banip"
--- | "banname"
--- | "bans"
--- | "bansteam"
--- | "banusgn"
--- | "bind"
--- | "bot"
--- | "bot_add"
--- | "bot_add_ct"
--- | "bot_add_t"
--- | "bot_autofill"
--- | "bot_count"
--- | "bot_freeze"
--- | "bot_jointeam"
--- | "bot_keepfreeslots"
--- | "bot_kill"
--- | "bot_prefix"
--- | "bot_remove"
--- | "bot_remove_all"
--- | "bot_remove_ct"
--- | "bot_remove_t"
--- | "bot_skill"
--- | "bot_weapons"
--- | "bullets"
--- | "buy"
--- | "buyammo1"
--- | "buyammo2"
--- | "buyequip"
--- | "changelevel"
--- | "changemap"
--- | "chooseteam"
--- | "clear"
--- | "clientport"
--- | "close"
--- | "cmsg"
--- | "connection"
--- | "connections"
--- | "console"
--- | "copyaddress"
--- | "customkill"
--- | "damageobject"
--- | "damagetile"
--- | "deagle"
--- | "deathnoticeimg"
--- | "deathslap"
--- | "debug"
--- | "debugai"
--- | "debuglog"
--- | "debuglua"
--- | "debugstats"
--- | "defuser"
--- | "disconnect"
--- | "dmgindicator"
--- | "download"
--- | "drawradar"
--- | "drop"
--- | "echo"
--- | "effect"
--- | "elite"
--- | "elites"
--- | "endround"
--- | "equip"
--- | "exec"
--- | "exit"
--- | "explosion"
--- | "famas"
--- | "flare"
--- | "flash"
--- | "flashlight"
--- | "flashplayer"
--- | "flashposition"
--- | "fn57"
--- | "forward"
--- | "fowalpha"
--- | "fowdetails"
--- | "fps"
--- | "freeprojectile"
--- | "g3sg1"
--- | "galil"
--- | "glock"
--- | "gore"
--- | "grenademode"
--- | "hegren"
--- | "hudtxt"
--- | "hudtxt2"
--- | "hudtxtalphafade"
--- | "hudtxtclear"
--- | "hudtxtcolorfade"
--- | "hudtxtmove"
--- | "hud_fastswitch"
--- | "hud_takesshots"
--- | "include"
--- | "invnext"
--- | "invprev"
--- | "items"
--- | "itemshadows"
--- | "kick"
--- | "kill"
--- | "killobject"
--- | "killplayer"
--- | "lastinv"
--- | "left"
--- | "lefthand"
--- | "listbans"
--- | "listplayers"
--- | "localport"
--- | "logaddress_add"
--- | "logaddress_remove"
--- | "logaddress_removeall"
--- | "logbatch"
--- | "logmaxflushrate"
--- | "logsplit"
--- | "logstamp"
--- | "lua"
--- | "luareset"
--- | "m249"
--- | "m3"
--- | "m4a1"
--- | "mac10"
--- | "makect"
--- | "makespec"
--- | "maket"
--- | "map"
--- | "mapinfo"
--- | "maps"
--- | "mapshadows"
--- | "mapsounds"
--- | "markplayer"
--- | "memory"
--- | "menuselect"
--- | "menu_lanscanport"
--- | "mp5"
--- | "mp_antispeeder"
--- | "mp_autogamemode"
--- | "mp_autoteambalance"
--- | "mp_building_health"
--- | "mp_building_limit"
--- | "mp_building_price"
--- | "mp_buymenu"
--- | "mp_buytime"
--- | "mp_c4timer"
--- | "mp_connectionlimit"
--- | "mp_curtailedexplosions"
--- | "mp_damagefactor"
--- | "mp_deathdrop"
--- | "mp_dispenser_health"
--- | "mp_dispenser_money"
--- | "mp_dmspawnmoney"
--- | "mp_dropgrenades"
--- | "mp_flashlight"
--- | "mp_floodprot"
--- | "mp_floodprotignoretime"
--- | "mp_freezetime"
--- | "mp_grenaderebuy"
--- | "mp_hostagepenalty"
--- | "mp_hovertext"
--- | "mp_hud"
--- | "mp_hudscale"
--- | "mp_idleaction"
--- | "mp_idlekick"
--- | "mp_idletime"
--- | "mp_infammo"
--- | "mp_kevlar"
--- | "mp_kickpercent"
--- | "mp_killbuildingmoney"
--- | "mp_killbuildings"
--- | "mp_killinfo"
--- | "mp_killteambuildings"
--- | "mp_lagcompensation"
--- | "mp_lagcompensationdivisor"
--- | "mp_localrconoutput"
--- | "mp_luamap"
--- | "mp_luaserver"
--- | "mp_mapgoalscore"
--- | "mp_mapvoteratio"
--- | "mp_maxclientsip"
--- | "mp_maxrconfails"
--- | "mp_natholepunching"
--- | "mp_pinglimit"
--- | "mp_postspawn"
--- | "mp_radar"
--- | "mp_randomspawn"
--- | "mp_recoil"
--- | "mp_reservations"
--- | "mp_respawndelay"
--- | "mp_roundlimit"
--- | "mp_roundtime"
--- | "mp_shotweakening"
--- | "mp_smokeblock"
--- | "mp_startmoney"
--- | "mp_supply_items"
--- | "mp_teamkillpenalty"
--- | "mp_teleportreload"
--- | "mp_tempbantime"
--- | "mp_timelimit"
--- | "mp_tkpunish"
--- | "mp_trace"
--- | "mp_turretdamage"
--- | "mp_unbuildable"
--- | "mp_unbuyable"
--- | "mp_vulnerablehostages"
--- | "mp_weaponfadeout"
--- | "mp_winlimit"
--- | "mp_wpndmg"
--- | "mp_wpndmg_z1"
--- | "mp_wpndmg_z2"
--- | "mp_zombiedmg"
--- | "mp_zombiekillequip"
--- | "mp_zombiekillscore"
--- | "mp_zombierecover"
--- | "mp_zombiespeedmod"
--- | "msg"
--- | "name"
--- | "netinfo"
--- | "nick"
--- | "nightvision"
--- | "nvgs"
--- | "p228"
--- | "p90"
--- | "particles"
--- | "playershadows"
--- | "quit"
--- | "radio1"
--- | "radio2"
--- | "radio3"
--- | "rcon"
--- | "rcon_password"
--- | "rcon_pw"
--- | "rebuy"
--- | "recoil"
--- | "relativemovement"
--- | "reload"
--- | "removeitem"
--- | "render3d"
--- | "renderdecals"
--- | "renderdecoration"
--- | "reroute"
--- | "resources"
--- | "restart"
--- | "restartround"
--- | "right"
--- | "say"
--- | "sayteam"
--- | "scout"
--- | "screenshot"
--- | "server"
--- | "serveraction1"
--- | "serveraction2"
--- | "serveraction3"
--- | "serverinfo"
--- | "setammo"
--- | "setarmor"
--- | "setassists"
--- | "setdeaths"
--- | "sethealth"
--- | "setmaxhealth"
--- | "setmoney"
--- | "setmvp"
--- | "setname"
--- | "setpos"
--- | "setscore"
--- | "setteamscores"
--- | "settile"
--- | "setweapon"
--- | "SG550"
--- | "sg552"
--- | "sgren"
--- | "shadows"
--- | "shadowshade_obstacle"
--- | "shadowshade_wall"
--- | "shadowz_obstacles"
--- | "shadowz_wall"
--- | "shadow_angle"
--- | "shadow_frameskipping"
--- | "shake"
--- | "shield"
--- | "showscores"
--- | "slap"
--- | "slot0"
--- | "slot1"
--- | "slot10"
--- | "slot2"
--- | "slot3"
--- | "slot4"
--- | "slot5"
--- | "slot6"
--- | "slot7"
--- | "slot8"
--- | "slot9"
--- | "snapshot"
--- | "sounddriver"
--- | "soundmode"
--- | "spawnitem"
--- | "spawnnpc"
--- | "spawnobject"
--- | "spawnplayer"
--- | "spawnprojectile"
--- | "specmode"
--- | "specplayer"
--- | "speed"
--- | "speedmod"
--- | "spray"
--- | "spraycolor"
--- | "spraylogo"
--- | "strip"
--- | "sv_checkusgnlogin"
--- | "sv_daylighttime"
--- | "sv_forcelight"
--- | "sv_fow"
--- | "sv_friendlyfire"
--- | "sv_gamemode"
--- | "sv_gm"
--- | "sv_hostport"
--- | "sv_lan"
--- | "sv_map"
--- | "sv_maptransfer"
--- | "sv_maxplayers"
--- | "sv_msg"
--- | "sv_msg2"
--- | "sv_name"
--- | "sv_offscreendamage"
--- | "sv_password"
--- | "sv_physics"
--- | "sv_rcon"
--- | "sv_rconusers"
--- | "sv_restart"
--- | "sv_restartround"
--- | "sv_sound"
--- | "sv_sound2"
--- | "sv_soundpos"
--- | "sv_specmode"
--- | "sv_spraytransfer"
--- | "sv_stopsound"
--- | "sv_usgnonly"
--- | "sv_voicechat"
--- | "team"
--- | "tileanimations"
--- | "tmp"
--- | "transfer_speed"
--- | "trigger"
--- | "triggerposition"
--- | "ump45"
--- | "unban"
--- | "unbanall"
--- | "unbindall"
--- | "use"
--- | "usgn_addserver"
--- | "usgn_info"
--- | "usgn_pw"
--- | "usgn_user"
--- | "usp"
--- | "vest"
--- | "vesthelm"
--- | "visibleshots"
--- | "volume"
--- | "vote"
--- | "votemap"
--- | "votemenu"
--- | "weapon"
--- | "wiggle"
--- | "win"
--- | "xm1014"

--- @todo document each command
--- Console Settings that can be accessed by the [game](lua://game) function.
--- @alias setting_command
--- | "version" # `string`: the current game version.
--- | "dedicated" # `boolean`: `true` if server is dedicated, `false` otherwise.
--- | "phase" # `number`: game phase (`0` for freezetime, `1` for actual game).
--- | "round" # `number`: current round.
--- | "timeleft" # `number`: remaining round time in seconds.
--- | "maptimeleft" # `number`: remaining time on map in seconds (float precision), `1000000` if unlimited.
--- | "score_t" # `number`: score of terrorists (rounds won).
--- | "score_ct" # `number`: score of counter-terrorists (rounds won).
--- | "winrow_t" # `number`: rounds won in a row by terrorists.
--- | "winrow_ct" # `number`: rounds won in a row by counter-terrorists.
--- | "nextmap" # `string`: the next map in the map cycle.
--- | "ticks" # `number`: server ticks (refresh rate / main-loop iterations per second).
--- | "port" # `string`: UDP port used by the server (`"no socket"` if failed to open port).
--- | "bombplanted" # `boolean`: `true` if bomb is currently planted and blinking, `false` otherwise.
--- | "sysfolder" # `string`: the system folder/path (`"sys"` by default, custom value if specified via commandline).
--- | "ah"
--- | "autoscreen"
--- | "autoswitch"
--- | "bot_count"
--- | "bot_prefix"
--- | "bot_skill"
--- | "bot_weapons"
--- | "bullets"
--- | "debug"
--- | "debugai"
--- | "debuglog"
--- | "debuglua"
--- | "dmgindicator"
--- | "drawradar"
--- | "fowalpha"
--- | "fowdetails"
--- | "gore"
--- | "grenademode"
--- | "hud_fastswitch"
--- | "itemshadows"
--- | "localport"
--- | "logbatch"
--- | "logmaxflushrate"
--- | "logsplit"
--- | "logstamp"
--- | "mapshadows"
--- | "mapsounds"
--- | "markplayer"
--- | "menu_lanscanport"
--- | "mp_anticlock"
--- | "mp_antispeeder"
--- | "mp_autogamemode"
--- | "mp_autoteambalance"
--- | "mp_buytime"
--- | "mp_c4timer"
--- | "mp_connectionlimit"
--- | "mp_curtailedexplosions"
--- | "mp_damagefactor"
--- | "mp_deathdrop"
--- | "mp_dispenser_health"
--- | "mp_dispenser_money"
--- | "mp_dmspawnmoney"
--- | "mp_dropgrenades"
--- | "mp_flashlight"
--- | "mp_floodprot"
--- | "mp_floodprotignoretime"
--- | "mp_freezetime"
--- | "mp_grenaderebuy"
--- | "mp_hostagepenalty"
--- | "mp_hovertext"
--- | "mp_hud"
--- | "mp_hudscale"
--- | "mp_idleaction"
--- | "mp_idlekick"
--- | "mp_idletime"
--- | "mp_infammo"
--- | "mp_kevlar"
--- | "mp_kickpercent"
--- | "mp_killbuildingmoney"
--- | "mp_killbuildings"
--- | "mp_killinfo"
--- | "mp_killteambuildings"
--- | "mp_lagcompensation"
--- | "mp_lagcompensationdivisor"
--- | "mp_localrconoutput"
--- | "mp_luamap"
--- | "mp_luaserver"
--- | "mp_mapgoalscore"
--- | "mp_mapvoteratio"
--- | "mp_maxclientsip"
--- | "mp_maxrconfails"
--- | "mp_natholepunching"
--- | "mp_pinglimit"
--- | "mp_postspawn"
--- | "mp_radar"
--- | "mp_randomspawn"
--- | "mp_recoil"
--- | "mp_respawndelay"
--- | "mp_roundlimit"
--- | "mp_roundtime"
--- | "mp_shotweakening"
--- | "mp_smokeblock"
--- | "mp_startmoney"
--- | "mp_supply_items"
--- | "mp_teamkillpenalty"
--- | "mp_teleportreload"
--- | "mp_tempbantime"
--- | "mp_timelimit"
--- | "mp_tkpunish"
--- | "mp_trace"
--- | "mp_turretdamage"
--- | "mp_unbuyable"
--- | "mp_vulnerablehostages"
--- | "mp_weaponfadeout"
--- | "mp_winlimit"
--- | "mp_zombiedmg"
--- | "mp_zombiekillequip"
--- | "mp_zombiekillscore"
--- | "mp_zombierecover"
--- | "mp_zombiespeedmod"
--- | "name"
--- | "particles"
--- | "playershadows"
--- | "recoil"
--- | "relativemovement"
--- | "renderdecals"
--- | "renderdecoration"
--- | "shadows"
--- | "shadowshade_obstacle"
--- | "shadowshade_wall"
--- | "soundmode"
--- | "spraycolor"
--- | "spraylogo"
--- | "sv_checkusgnlogin"
--- | "sv_daylighttime"
--- | "sv_fow"
--- | "sv_friendlyfire"
--- | "sv_gamemode"
--- | "sv_hostport"
--- | "sv_lan"
--- | "sv_map"
--- | "sv_maptransfer"
--- | "sv_maxplayers"
--- | "sv_name"
--- | "sv_offscreendamage"
--- | "sv_password"
--- | "sv_rcon"
--- | "sv_specmode"
--- | "sv_spraytransfer"
--- | "sv_usgnonly"
--- | "tileanimations"
--- | "transfer_speed"
--- | "visibleshots"
--- | "volume"
--- | "wiggle"

--- List of valid entity function queries.
--- @alias entity_value_params
--- | "exists" # Boolean, `true` if there is an entity at this position, `false` otherwise
--- | "typename" # Name of that entity type
--- | "type" # Internal type identifier for that entity
--- | "name" # Name entered in the name field of that entity
--- | "trigger" # Value(s) entered in the trigger field of that entity
--- | "state" # Boolean, `false` if visible/on (default), `true` otherwise
--- | "int0" # Internal number for settings/states
--- | "int1" # Internal number for settings/states
--- | "int2" # Internal number for settings/states
--- | "int3" # Internal number for settings/states
--- | "int4" # Internal number for settings/states
--- | "int5" # Internal number for settings/states
--- | "int6" # Internal number for settings/states
--- | "int7" # Internal number for settings/states
--- | "int8" # Internal number for settings/states
--- | "int9" # Internal number for settings/states
--- | "str0" # Internal string for settings/states
--- | "str1" # Internal string for settings/states
--- | "str2" # Internal string for settings/states
--- | "str3" # Internal string for settings/states
--- | "str4" # Internal string for settings/states
--- | "str5" # Internal string for settings/states
--- | "str6" # Internal string for settings/states
--- | "str7" # Internal string for settings/states
--- | "str8" # Internal string for settings/states
--- | "str9" # Internal string for settings/states
--- | "aistate" # AI state for AI scripting, can be set with `setentityaistate`

--- List of entities.
--- @alias entity_type_ids
--- | 0 # Info_T
--- | 1 # Info_CT
--- | 2 # Info_VIP
--- | 3 # Info_Hostage
--- | 4 # Info_RescuePoint
--- | 5 # Info_BombSpot
--- | 6 # Info_EscapePoint
--- | 8 # Info_Animation
--- | 9 # Info_Storm
--- | 10 # Info_TileFX
--- | 11 # Info_NoBuying
--- | 12 # Info_NoWeapons
--- | 13 # Info_NoFOW
--- | 14 # Info_Quake
--- | 15 # Info_CTF_Flag
--- | 16 # Info_OldRender
--- | 17 # Info_Dom_Point
--- | 18 # Info_NoBuildings
--- | 19 # Info_BotNode
--- | 20 # Info_TeamGate
--- | 21 # Env_Item
--- | 22 # Env_Sprite
--- | 23 # Env_Sound
--- | 24 # Env_Decal
--- | 25 # Env_Breakable
--- | 26 # Env_Explode
--- | 27 # Env_Hurt
--- | 28 # Env_Image
--- | 29 # Env_Object
--- | 30 # Env_Building
--- | 31 # Env_NPC
--- | 32 # Env_Room
--- | 33 # Env_Light
--- | 34 # Env_LightStripe
--- | 50 # Gen_Particles
--- | 51 # Gen_Sprites
--- | 52 # Gen_Weather
--- | 53 # Gen_FX
--- | 70 # Func_Teleport
--- | 71 # Func_DynWall
--- | 72 # Func_Message
--- | 73 # Func_GameAction
--- | 80 # Info_NoWeather
--- | 90 # Trigger_Start
--- | 91 # Trigger_Move
--- | 92 # Trigger_Hit
--- | 93 # Trigger_Use
--- | 94 # Trigger_Delay
--- | 95 # Trigger_Once
--- | 96 # Trigger_If

--- List of valid hostage function queries.
--- @alias hostage_value_params
--- | "exists" # Boolean, `true` if hostage with this identifier exists, `false` otherwise
--- | "health" # Number, Hostage health (`0`-`100`)
--- | "follow" # Number, player identifier if the hostage is following a player, `0` otherwise
--- | "used" # Boolean, `true` if the hostage has been used by a counter-terrorist this round, `false` otherwise
--- | "look" # Number, hostage look (skin frame)
--- | "x" # Number, current `X` position on map (in pixels)
--- | "y" # Number, current `Y` position on map (in pixels)
--- | "rot" # Number, current rotation angle
--- | "tilex" # Number, current `X` position on map (in tiles)
--- | "tiley" # Number, current `Y` position on map (in tiles)

--- List of image draw modes.
--- @alias image_draw_modes
--- | 0 # Floor image (covered by players)
--- | 1 # Top image (covering players)
--- | 2 # HUD image (covering everything, part of the interface, affected by `mp_hudscale`)
--- | 3 # Super top image (covering everything on the map)
--- | 4 # Background image (covering only the background)
--- | 100 # Draw at player, covered by player (player `id+100`)
--- | 200 # Draw at player, covering player (player `id+200`)
--- | 132 # Draw at player, covering player and entity images (player `id+132`)

--- List of image blend modes.
--- @alias image_blend_modes
--- | 0 # Normal (default)
--- | 1 # Additive (brightens underlying colours)
--- | 2 # Subtractive (darkens underlying colours)
--- | 3 # Multiply (darkens colours)
--- | 4 # Screen (brightens colours)
--- | 5 # Invert (inverts the colour)
--- | 6 # Overlay (combines multiply and screen effects)

--- List of image blend modes.
--- **Non-Blocking Modes (<= `100`, shots will pass through):**
--- @alias image_hitzone_modes_non_blocking
--- | 0 # Removes any existing hit zones (other parameters don't matter).
--- | 1 # Hit zone without effects (just registers the zone).
--- | 2 # Wall effect (hit zone causes a wall effect).
--- | 3 # Blood effect (hit zone triggers blood effect).
--- | 4 # Green blood effect (hit zone triggers green blood effect).

--- **Blocking Modes (> `100`, shots will be stopped):**
--- @alias image_hitzone_modes_blocking
--- | 101 # Hit zone without effects + stop shot.
--- | 102 # Wall effect + stop shot.
--- | 103 # Blood effect + stop shot.
--- | 104 # Green blood effect + stop shot.

--- **Collision Blocking Modes (> `200`, shots will be stopped and players will collide):**
--- @alias image_hitzone_modes_collision_blocking
--- | 201 # Hit zone without effects + stop shot + collide.
--- | 202 # Wall effect + stop shot + collide.
--- | 203 # Blood effect + stop shot + collide.
--- | 204 # Green blood effect + stop shot + collide.

--- @alias image_hitzone_modes
--- | image_hitzone_modes_non_blocking
--- | image_hitzone_modes_blocking
--- | image_hitzone_modes_collision_blocking

--- @alias imageparam_params
--- | "x" # The X-position of the image on the map (in pixels). The meaning can change depending on the image mode.
--- | "y" # The Y-position of the image on the map (in pixels). The meaning can change depending on the image mode.
--- | "rot" # The current rotation angle of the image (in degrees). Returns `0` if the image is not rotated.
--- | "alpha" # The alpha transparency value of the image, ranging from `0.0` (completely transparent) to `1.0` (completely opaque).
--- | "path" # The string path to the image (e.g., "gfx/sprites/flare.png").
--- | "frame" # The current animation frame of the image (for images with multiple frames).
--- | "width" # The width of the image in pixels.
--- | "height" # The height of the image in pixels.
--- | "framecount" # The total number of animation frames for the image.

--- @alias item_params
--- | "exists" # `boolean`, `true` if an item with that identifier exists, `false` otherwise.
--- | "name" # The name of the item.
--- | "type" # Internal item type identifier.
--- | "player" # identifier of the player that carries this item, or `0` if it is dropped.
--- | "ammo" # The ammo supply for that weapon (not loaded into it).
--- | "ammoin" # Ammo currently loaded into the weapon.
--- | "mode" # Weapon mode (e.g., colour of laser, silenced or not).
--- | "x" # X position of the dropped weapon on the map (in **tiles**).
--- | "y" # Y position of the dropped weapon on the map (in **tiles**).
--- | "dropped" # `boolean`, `true` if the weapon has been dropped by a player, `false` otherwise.
--- | "droptimer" # How long ago the weapon was dropped (in seconds).

--- @alias item_type_params
--- | "name" # The name of the item, returns an empty string (`""`) if no item with this type exists.
--- | "dmg" # The damage caused by this item.
--- | "dmg_z1" # The damage caused with zoom level 1 (secondary attack mode).
--- | "dmg_z2" # The damage caused with zoom level 2.
--- | "rate" # The fire rate of the weapon.
--- | "reload" # The reload duration for the weapon.
--- | "ammo" # The amount of ammo that can be carried with the weapon.
--- | "ammoin" # The amount of ammo that can be loaded into the weapon.
--- | "price" # The price of the item.
--- | "range" # The weapon range.
--- | "dispersion" # The weapon dispersion.
--- | "slot" # The item HUD slot.
--- | "recoil" # The weapon recoil.

--- @alias map_params
--- | "name" # The name of the map.
--- | "xsize" # The x size of the map in tiles.
--- | "ysize" # The y size of the map in tiles.
--- | "tileset" # The tile-set file used in the map.
--- | "tilesize" # The size of each tile in the tile-set (either 32 or 64 pixels).
--- | "tilecount" # The number of tiles in the tile-set.
--- | "back_img" # The background image for the map (empty if there is none).
--- | "back_scrollx" # The x scrolling speed of the background.
--- | "back_scrolly" # The y scrolling speed of the background.
--- | "back_scrolltile" # Whether the background scrolls like tiles (0 or 1).
--- | "back_r" # The red value for the background colour.
--- | "back_g" # The green value for the background colour.
--- | "back_b" # The blue value for the background colour.
--- | "storm_x" # The x speed of the storm.
--- | "storm_y" # The y speed of the storm.
--- | "mission_vips" # The number of VIP spawns.
--- | "mission_hostages" # The number of hostages.
--- | "mission_bombspots" # The number of bomb spots.
--- | "mission_ctfflags" # The number of CTF flags.
--- | "mission_dompoints" # The number of domination points.
--- | "nobuying" # Whether buying is allowed (0 or 1).
--- | "noweapons" # Whether weapons are allowed (0 or 1).
--- | "teleporters" # Whether there are teleporters (0 or 1).
--- | "botnodes" # The number of bot nodes.

--- @alias object_params
--- | "table" # Returns a list of all dynamic objects when the object ID is set to `0`.
--- | "exists" # Returns `true` if the object exists, `false` otherwise.
--- | "typename" # The name of the object's type.
--- | "type" # Internal type identifier of the object (reference image [here](https://cs2d.com/img/ref_dynamicobjects.png)).
--- | "health" # The current health value of the object.
--- | "mode" # The current mode of the object, which can vary depending on the object type.
--- | "team" # The team the object belongs to (reference image [here](https://cs2d.com/img/ref_team.png)).
--- | "player" # The player who created or owns the object, or for NPCs, the NPC type (reference [here](https://cs2d.com/img/ref_npcs.png)).
--- | "x" # The current x-position of the object in pixels.
--- | "y" # The current y-position of the object in pixels.
--- | "rot" # The current rotation angle of the object.
--- | "alpha" # The alpha transparency value (`0.0` to `1.0`).
--- | "tilex` and `tiley" # Tile position (`tx` and `ty`) on the map.
--- | "countdown" # The countdown value associated with the object.
--- | "rootrot" # The original rotation of the object.
--- | "idle" # The idle state for the object.
--- | "rotvar" # The rotation variation.
--- | "target" # Identifier of the object's current target.
--- | "upgrade" # Upgrade value of the object.
--- | "entity" # `true` if the object is spawned by an entity, `false` otherwise.
--- | "entityx` and `entityy" # Tile coordinates of the entity that spawned the object.

--- @alias objecttype_params
--- | "name" # The localized name of the object (may change depending on server's language setting).
--- | "internalname" # The internal name of the object. This will be an empty string (`""`) if no object exists with this type.
--- | "type" # The subtype/class of the object:
---   - `1` # building
---   - `2` # stuff (mines, portals, etc.)
---   - `3` # NPC unit
---   - `4` # image
--- | "price" # The price of the object (used for buildings).
--- | "health" # The maximum or initial health of the object.
--- | "killmoney" # The amount of money a player receives for killing or destroying the object.
--- | "limit" # The maximum number of buildings of this type a player can build.
--- | "upgradepoints" # The number of hits required to upgrade this building (0 if there is no upgrade).
--- | "upgradeprice" # The price for upgrading the building (calculated as `upgrade_points * 50`; `0` if no upgrade is available).
--- | "upgradeto" # The object type identifier to which this building can be upgraded (`0` if no upgrade is available).

--- @alias player_identify_logins_language_params
--- | "exists" # `boolean`, `true` if player with this identifier exists, `false` otherwise.
--- | "name" # Name of the player.
--- | "ip" # IP address of the player or "`0.0.0.0`" for bots/server.
--- | "port" # Port of the player.
--- | "usgn" # Unreal Software Gaming Network / UnrealSoftware.de user identifier (`0` if not logged in).
--- | "usgnname" # Unreal Software Gaming Network / UnrealSoftware.de username (`""` if not logged in).
--- | "steamid" # Steam identifier as a string (`"0"` if not logged in).
--- | "steamname" # Steam username (`""` if not logged in or if name retrieval failed).
--- | "bot" # `boolean`, `true` if player is a bot, `false` otherwise.
--- | "rcon" # `boolean`, `true` if logged in with correct RCon password, `false` otherwise.
--- | "language" # Current language of the player as a string.
--- | "language_iso" # Current language of the player as an ISO code string.

--- @alias player_team_appearance_params
--- | "team" # `0` for spectators, `1` for terrorists, `2` for counter-terrorists, `3` for VIP (CT).
--- | "favteam" # Favourite team if preferred team joining fails (e.g., in Zombies! mode).
--- | "look" # Player look (`0`-`3`) / selected faction skin.
--- | "sprayname" # Name of spray logo file.
--- | "spraycolor" # Colour of spray logo (0-based index, reference in options menu).

--- @alias player_mouse_position_screen_setup_params
--- | "mousex"# Player mouse `X` screen position (alive players only, `-1` if not available).
--- | "mousey" # Player mouse `Y` screen position (alive players only, `-1` if not available).
--- | "mousemapx" # Mouse `X` position on the map (alive players only, `-1` if not available).
--- | "mousemapy" # Mouse `Y` position on the map (alive players only, `-1` if not available).
--- | "mousedist" # Distance between player and mouse (alive players only, `-1` if not available).
--- | "screenw" # Game screen width dimensions in pixels (excluding borders).
--- | "screenh" # Game screen height dimensions in pixels (excluding borders).
--- | "widescreen" # Game running mode: widescreen (`0`/`1`).
--- | "windowed" # Game running mode: windowed (`0`/`1`).
--- | "micsupport" # `0`/`1`, indicates microphone support.

--- @alias player_position_params
--- | "x" # Current `X` position on the map (in pixels).
--- | "y" # Current `Y` position on the map (in pixels).
--- | "tilex" # Current `X` position on the map (in **tiles**).
--- | "tiley" # Current `Y` position on the map (in **tiles**).
--- | "rot" # Current rotation angle.

--- @alias player_stats_params
--- | "health" # Current health value.
--- | "maxhealth" # Maximum health value.
--- | "armor" # Armour value (see extended details for specific armour types).
---     - `0`-`200`: Regular Kevlar(+Helm) points (damage reduction, decreases on hit).
---     - `201`-`206`: Specialized armours with unique damage reductions and effects.
--- | "money" # Money value.
--- | "score" # Player score.
--- | "deaths" # Player deaths.
--- | "teamkills" # Player team kills.
--- | "hostagekills" # Hostages killed.
--- | "teambuildingkills" # Teammate buildings destroyed.
--- | "mvp" # Rounds as MVP.
--- | "assists" # Number of kill assists.
--- | "ping" # Current ping in milliseconds.
--- | "idle" # Idle time in seconds (int).
--- | "speedmod" # Speed modifier value (`0` = normal, `<0` = slower, `>0` = faster).
--- | "spectating" # Identifier of the player currently spectated.
--- | "ai_flash" # Flashbang duration for bots (seconds, float, `0` if not flashed).

--- @alias player_equipment_params
--- | "weapontype" # Type ID of the current weapon.
--- | "weaponmode" # Mode of the current weapon.
--- | "nightvision" # Possession of night vision as `boolean` value.
--- | "defusekit" # Possession of defuse kit as `boolean` value.
--- | "gasmask" # Possession of gas mask as `boolean` value.
--- | "bomb" # Possession of bomb as `boolean` value.
--- | "flag" # Possession of flag as `boolean` value.

--- @alias player_action_voting_params
--- | "reloading" # `boolean`, `true` if reloading.
--- | "process" # Current process state (internal ID for reloading/planting/defusing).
---     - Values from `1`-`6` represent specific states (e.g., `1` = Start bomb planting).
--- | "votekick" # Voted kick player ID (`0` if no vote).
--- | "votemap" # Voted map name (empty string if no vote).

--- @alias player_tables_params
--- | "table" # All player identifiers.
--- | "tableliving" # All living player identifiers.
--- | "team1" # Terrorist identifiers.
--- | "team2" # Counter-Terrorist identifiers.
--- | "team1living" # Living Terrorist identifiers.
--- | "team2living" # Living Counter-Terrorist identifiers.

--- @alias player_params
--- | player_identify_logins_language_params
--- | player_team_appearance_params
--- | player_mouse_position_screen_setup_params
--- | player_position_params
--- | player_stats_params
--- | player_equipment_params
--- | player_action_voting_params
--- | player_tables_params

--- @alias projectile_params
--- | "exists" # `boolean`, `true` if the projectile exists, `false` otherwise.
--- | "type" # Internal type identifier (matches the weapon's corresponding identifier).
--- | "x" # Current `X` position on the map (in pixels).
--- | "y" # Current `Y` position on the map (in pixels).
--- | "dir" # Current flight direction.
--- | "rot" # Current rotation angle (used for visual effects only).
--- | "flydist" # Distance (in pixels) the projectile will fly (applies to flying projectiles).
--- | "time" # Countdown (in seconds) until the projectile is removed (applies to ground projectiles).

--- @alias reqcld_params
--- | 0 # Cursor position on screen (in pixels, scaled based on `mp_hudscale`).
---   - **Deprecated**: Use `player` with "mousex"/"mousey" instead.
--- | 1 # Map scrolling offset (in pixels).
--- | 2 # Absolute cursor position on the map (in pixels, not influenced by `mp_hudscale`).
---   - **Deprecated**: Use `player` with "mousemapx"/"mousemapy" instead.
--- | 3 # Advanced light engine state (`1` if enabled, `0` otherwise; second value is always `0`).
--- | 4 # File load status and checksum.
---   - Returns `1` if the file (specified with `param`) is loaded, `0` otherwise.
---   - If the file is under `gfx/` or `sfx/`, also returns the checksum as provided by `checksumfile`.
--- | 5 # Mod information.
--- | 6 # 3D rendering state (`1` if enabled, `0` otherwise; second value is always `0`).

--- @alias stats_params
--- | "exists" # `boolean`, `true` if stats for the U.S.G.N. identifier are available, `false` otherwise.
--- | "rank" # Current rank of the player on the server (`1` for the best, `0` if unranked).
--- | "killsperdeath" # Kills per death ratio (calculated as `kills / deaths`).
--- | "score" # Total score (sum of map mission goal score and frags).
--- | "frags" # Number of kills.
--- | "deaths" # Number of deaths.
--- | "secs" # Time spent on the server in seconds (only counts time while in a team, excludes time as spectator).
--- | "mvp" # Number of rounds where the player was the most valuable player.
--- | "assists" # Number of kill assists.

--- @alias tile_params
--- | "frame" # Tile frame number in the tileset currently applied to this tile.
--- | "property" # Tile type, representing the material/behaviour of the tile:
---   - `0`: Tile without sound.
---   - `1`: Wall.
---   - `2`: Obstacle.
---   - `3`: Wall without shadow.
---   - `4`: Obstacle without shadow.
---   - `5`: Floor wall.
---   - `10`: Dirt floor.
---   - `11`: Snow floor.
---   - `12`: Step floor.
---   - `13`: Tile floor.
---   - `14`: Wade floor.
---   - `15`: Metal floor.
---   - `16`: Wood floor.
---   - `50`: Deadly.
---   - `51`: Toxic deadly.
---   - `52`: Explosion deadly.
---   - `53`: Abyss deadly.
--- | "walkable" # `boolean`, `true` if walkable, `false` otherwise.
--- | "deadly" # `boolean`, `true` if deadly, `false` otherwise.
--- | "wall" # `boolean`, `true` if wall, `false` otherwise.
--- | "obstacle" # `boolean`, `true` if obstacle, `false` otherwise.
--- | "entity" # `number`, entity type at this position (`0` if none, `>0` otherwise).
--- | "hascustomframe" # `boolean`, `true` if the frame has been changed with `settile`, `false` otherwise.
--- | "originalframe" # Tile frame number originally assigned (unaltered map) or currently assigned if not changed.
--- | "rot" # Tile rotation in degrees (`0` if not rotated; `90`, `180`, or `270` otherwise).
--- | "blend" # Tile blending frame, or `false` if not blended.
--- | "color" # `table`, Lua table with `r`, `g`, `b` values of the tile, or `false` if no custom colour is set (default is `r=255`, `g=255`, `b=255`).
--- | "brightness" # Custom brightness level (`0, 10, 20, ..., 100`), or `false` if not set (default is `100`).

--- @alias tile_properties
--- | 0 # Tile without sound.
--- | 1 # Wall.
--- | 2 # Obstacle.
--- | 3 # Wall without shadow.
--- | 4 # Obstacle without shadow.
--- | 5 # Floor wall.
--- | 10 # Dirt floor.
--- | 11 # Snow floor.
--- | 12 # Step floor.
--- | 13 # Tile floor.
--- | 14 # Wade floor.
--- | 15 # Metal floor.
--- | 16 # Wood floor.
--- | 50 # Deadly.
--- | 51 # Toxic deadly.
--- | 52 # Explosion deadly.
--- | 53 # Abyss deadly.

--- @alias image_animation_modes
--- | 0 # Loop Forward (play from the current frame to the last frame, then restart from the first frame).
--- | 1 # Loop Backward (play from the current frame to the first frame, then restart from the last frame).
--- | 2 # Ping Pong Forward (play forward to the last frame, then backward to the first frame, repeatedly).
--- | 3 # Ping Pong Backward (play backward to the first frame, then forward to the last frame, repeatedly).
--- | 4 # Random (display a random frame every `milliseconds`).

--- @alias player_image_rotation
--- | 0 # (or lower) do not rotate image with player **(player images only)**
--- | 1 # rotate image with player **(player images only)**
--- | 2 # rotate and wiggle image with player **(player images only)**
--- | 3 # rotate and wiggle image with player and move correctly with recoil

--- @alias player_image_fow
--- | 0 # (or lower) only draw if not covered by fog of war (always if fog of war is disabled) **(player images only)**
--- | 1 # (or higher) draw always **(player images only)**
